import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

import Featured from "~/components/featured/Featured";
import Professionals from "~/components/professionals/Professionals";
import Ideas from "~/components/ideas/Ideas";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Dev By Nate | Course Platform</title>
        <meta name="description " content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" h-screen w-full bg-background">
        <Featured />
        <Ideas />
        <Professionals/>
      </main>
    </>
  );
};

export default Home;
