import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import AuthShowcase from "~/components/auth-comp/AuthShowcase";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Dev By Nate | Course Platform</title>
        <meta name="description " content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" h-screen w-full bg-background">
        <div className="flex flex-col items-center gap-2">
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
